import os
from functools import lru_cache
from pathlib import Path

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")

MODEL_REPO = "buildborderless/CommunityForensics-DeepfakeDet-ViT"
MODEL_REVISION = "ac6ee457bea904a373065754107451793b56db00"
MODEL_FILE = "onnx/model.onnx"

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp"}

# CommunityForensics-DeepfakeDet-ViT preprocessing:
# RGB -> shortest edge 440 (preserve aspect ratio) -> center crop 384x384
# -> CLIP normalization -> NCHW float32.
IMAGE_SIZE = 384
RESIZE_SHORTER_EDGE = 440
CLIP_MEAN = (0.4815, 0.4578, 0.4082)
CLIP_STD = (0.2686, 0.2613, 0.2758)

# The corrected ONNX export is a single-logit binary classifier:
# sigmoid(logit) = fake / synthetic probability.
FAKE_THRESHOLD = 0.65
REAL_THRESHOLD = 0.35


@lru_cache(maxsize=1)
def _engine():
    import onnxruntime as ort
    from huggingface_hub import hf_hub_download

    model_path = hf_hub_download(
        repo_id=MODEL_REPO,
        filename=MODEL_FILE,
        revision=MODEL_REVISION,
    )

    options = ort.SessionOptions()
    options.intra_op_num_threads = 1
    options.inter_op_num_threads = 1
    options.execution_mode = ort.ExecutionMode.ORT_SEQUENTIAL
    options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC

    return ort.InferenceSession(
        model_path,
        sess_options=options,
        providers=["CPUExecutionProvider"],
    )


def _preprocess(path: Path):
    from PIL import Image
    import numpy as np

    with Image.open(path) as image:
        image = image.convert("RGB")
        width, height = image.size
        if min(width, height) <= 0:
            raise ValueError("That image has invalid dimensions.")

        scale = RESIZE_SHORTER_EDGE / min(width, height)
        resized_width = max(RESIZE_SHORTER_EDGE, int(width * scale))
        resized_height = max(RESIZE_SHORTER_EDGE, int(height * scale))
        image = image.resize(
            (resized_width, resized_height),
            Image.Resampling.BICUBIC,
        )

        left = (resized_width - IMAGE_SIZE) // 2
        top = (resized_height - IMAGE_SIZE) // 2
        image = image.crop(
            (left, top, left + IMAGE_SIZE, top + IMAGE_SIZE)
        )

        array = np.asarray(image, dtype=np.float32) / 255.0
        array = (
            array - np.asarray(CLIP_MEAN, dtype=np.float32)
        ) / np.asarray(CLIP_STD, dtype=np.float32)

    array = np.transpose(array, (2, 0, 1))
    return np.expand_dims(array, axis=0).astype(np.float32)


def _sigmoid(value: float) -> float:
    import numpy as np

    # Numerically stable sigmoid for a single model logit.
    if value >= 0:
        z = np.exp(-value)
        return float(1.0 / (1.0 + z))
    z = np.exp(value)
    return float(z / (1.0 + z))


def analyze_image(path: Path):
    import numpy as np

    session = _engine()
    input_name = session.get_inputs()[0].name
    input_tensor = _preprocess(path)

    outputs = session.run(None, {input_name: input_tensor})
    output = np.asarray(outputs[0], dtype=np.float32).reshape(-1)
    if output.size == 0:
        raise RuntimeError("The detector returned no output.")

    fake_probability = _sigmoid(float(output[0]))
    real_probability = 1.0 - fake_probability

    fake_pct = round(fake_probability * 100, 1)
    real_pct = round(real_probability * 100, 1)

    if fake_probability >= FAKE_THRESHOLD:
        status = "AI-GENERATED"
        label = "AI generated"
        confidence = round(fake_probability * 100)
        message = (
            "The image was classified as likely AI-generated by the "
            "CommunityForensics detection model."
        )
    elif fake_probability <= REAL_THRESHOLD:
        status = "LIKELY_REAL"
        label = "This image is likely real"
        confidence = round(real_probability * 100)
        message = (
            "The image was classified as likely real by the "
            "CommunityForensics detection model."
        )
    else:
        status = "UNCERTAIN"
        label = "Analysis inconclusive"
        confidence = round(max(fake_probability, real_probability) * 100)
        message = (
            "The model did not have enough evidence to confidently classify "
            "this image as real or AI-generated."
        )

    return {
        "status": status,
        "label": label,
        "score": confidence,
        "fake_probability": fake_pct,
        "real_probability": real_pct,
        "frames_analyzed": 1,
        "model": MODEL_REPO,
        "model_revision": MODEL_REVISION,
        "model_file": MODEL_FILE,
        "model_output": "single sigmoid logit",
        "message": message,
        "disclaimer": (
            "This is an automated model estimate, not a guarantee of "
            "authenticity. Results can be wrong, especially for images "
            "outside the model's training distribution."
        ),
    }


def analyze(path: Path):
    if path.suffix.lower() not in IMAGE_EXTS:
        return {
            "status": "COMING_SOON",
            "label": "Analysis coming soon",
            "score": None,
            "fake_probability": None,
            "real_probability": None,
            "signals": [],
            "message": (
                "Image analysis is available now. Video and audio analysis "
                "are not enabled by this detector."
            ),
            "disclaimer": "",
        }

    return analyze_image(path)
